// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjtdeqD_QZ7hxqMhHP_kPyNq1S7BIYzFk',
    appId: '1:238120144599:web:7fa414bc692ec83b622a92',
    messagingSenderId: '238120144599',
    projectId: 'fir-meet-test',
    authDomain: 'fir-meet-test.firebaseapp.com',
    storageBucket: 'fir-meet-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVXe_TdNAILjxt7eZAjUgOHZTPrdEfO2M',
    appId: '1:238120144599:android:f5107cd8dcbc57a2622a92',
    messagingSenderId: '238120144599',
    projectId: 'fir-meet-test',
    storageBucket: 'fir-meet-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB39QxlnzGU0EM7QM6zfqVXhBXYfVe9D-w',
    appId: '1:238120144599:ios:67c89d912ad1ee79622a92',
    messagingSenderId: '238120144599',
    projectId: 'fir-meet-test',
    storageBucket: 'fir-meet-test.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB39QxlnzGU0EM7QM6zfqVXhBXYfVe9D-w',
    appId: '1:238120144599:ios:7ec1c02857f4f76c622a92',
    messagingSenderId: '238120144599',
    projectId: 'fir-meet-test',
    storageBucket: 'fir-meet-test.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
